// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ETest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  //[Test]
  public void e() {
    driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/demo-site/checkout/");
    driver.Manage().Window.Size = new System.Drawing.Size(1239, 912);
    driver.FindElement(By.CssSelector(".payment_method_cheque > label")).Click();
    driver.FindElement(By.CssSelector(".payment_method_cod > label")).Click();
  }
}
