// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class FTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void f() {
    // Test name: f
    // Step # | name | target | value
    // 1 | open | /demo-site/cart/ | 
    driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/demo-site/cart/");
    // 2 | setWindowSize | 1250x916 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1250, 916);
    // 3 | click | css=td:nth-child(2) > .woocommerce-Price-amount > bdi | 
    driver.FindElement(By.CssSelector("td:nth-child(2) > .woocommerce-Price-amount > bdi")).Click();
    // 4 | click | css=label bdi | 
    driver.FindElement(By.CssSelector("label bdi")).Click();
    // 5 | click | name=apply_coupon | 
    driver.FindElement(By.Name("apply_coupon")).Click();
    // 6 | mouseOver | name=apply_coupon | 
    {
      var element = driver.FindElement(By.Name("apply_coupon"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 7 | mouseOut | name=apply_coupon | 
    {
      //var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
    //  builder.MoveToElement(element, 0, 0).Perform();
    }
    // 8 | click | css=.cart-discount .woocommerce-Price-amount | 
    driver.FindElement(By.CssSelector(".cart-discount .woocommerce-Price-amount")).Click();
    // 9 | click | css=label:nth-child(2) | 
    driver.FindElement(By.CssSelector("label:nth-child(2)")).Click();
    // 10 | click | css=strong bdi | 
    driver.FindElement(By.CssSelector("strong bdi")).Click();
    // 11 | click | css=.cart-subtotal > td | 
    driver.FindElement(By.CssSelector(".cart-subtotal > td")).Click();
  }
}
