// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void k() {
    driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/demo-site/cart/");
    driver.Manage().Window.Size = new System.Drawing.Size(1254, 916);
    driver.FindElement(By.CssSelector("td:nth-child(2) > .woocommerce-Price-amount > bdi")).Click();
    driver.FindElement(By.CssSelector(".cart-discount .woocommerce-Price-amount")).Click();
    driver.FindElement(By.CssSelector("label:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector("strong bdi")).Click();
  }
}
